# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170609_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
