# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170619_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='bought',
            field=models.BooleanField(default=False),
        ),
    ]
