# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.Item'),
        ),
    ]
