# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20170711_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
